BEGIN;

CREATE TABLE audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name TEXT NOT NULL,
  row_id TEXT NOT NULL,
  action TEXT NOT NULL CHECK (action IN ('INSERT', 'UPDATE', 'DELETE')),
  old_values JSONB,
  new_values JSONB,
  actor_user_id BIGINT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE OR REPLACE FUNCTION matapon_audit_row_change()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  actor_text TEXT;
  actor_id BIGINT;
  changed_row_id TEXT;
BEGIN
  actor_text := current_setting('matapon.actor_user_id', true);

  IF actor_text IS NOT NULL AND actor_text ~ '^[0-9]+$' THEN
    actor_id := actor_text::BIGINT;
  ELSE
    actor_id := NULL;
  END IF;

  IF TG_OP = 'DELETE' THEN
    changed_row_id := to_jsonb(OLD)->>'id';

    INSERT INTO audit_log (
      table_name,
      row_id,
      action,
      old_values,
      new_values,
      actor_user_id
    )
    VALUES (
      TG_TABLE_NAME,
      changed_row_id,
      'DELETE',
      to_jsonb(OLD),
      NULL,
      actor_id
    );

    RETURN OLD;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    changed_row_id := to_jsonb(NEW)->>'id';

    INSERT INTO audit_log (
      table_name,
      row_id,
      action,
      old_values,
      new_values,
      actor_user_id
    )
    VALUES (
      TG_TABLE_NAME,
      changed_row_id,
      'UPDATE',
      to_jsonb(OLD),
      to_jsonb(NEW),
      actor_id
    );

    RETURN NEW;
  END IF;

  changed_row_id := to_jsonb(NEW)->>'id';

  INSERT INTO audit_log (
    table_name,
    row_id,
    action,
    old_values,
    new_values,
    actor_user_id
  )
  VALUES (
    TG_TABLE_NAME,
    changed_row_id,
    'INSERT',
    NULL,
    to_jsonb(NEW),
    actor_id
  );

  RETURN NEW;
END;
$$;

DO $$
DECLARE
  table_name_to_audit TEXT;
BEGIN
  FOREACH table_name_to_audit IN ARRAY ARRAY[
    'users',
    'user_members',
    'event_types',
    'events',
    'event_type_others',
    'staff_members',
    'staff_areas',
    'staff_member_areas',
    'activities',
    'activity_others',
    'staff_activities',
    'event_activities',
    'event_activity_staff',
    'member_attendees',
    'event_activity_signups'
  ]
  LOOP
    EXECUTE format(
      'CREATE TRIGGER audit_row_change
       AFTER INSERT OR UPDATE OR DELETE ON %I
       FOR EACH ROW
       EXECUTE FUNCTION matapon_audit_row_change()',
      table_name_to_audit
    );
  END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION prevent_audit_log_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'audit_log is append-only';
END;
$$;

CREATE TRIGGER audit_log_no_update_delete
BEFORE UPDATE OR DELETE ON audit_log
FOR EACH ROW
EXECUTE FUNCTION prevent_audit_log_mutation();

CREATE TRIGGER audit_log_no_truncate
BEFORE TRUNCATE ON audit_log
FOR EACH STATEMENT
EXECUTE FUNCTION prevent_audit_log_mutation();

COMMIT;
