BEGIN;

CREATE TABLE areas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

INSERT INTO areas (name)
VALUES
  ('Waterfront'),
  ('Athletics'),
  ('Ropes'),
  ('Riding'),
  ('Arts'),
  ('Dining / Kitchen'),
  ('Guest Services'),
  ('Health Center'),
  ('Lodging / Cabins'),
  ('General Events');

ALTER TABLE activities
ADD COLUMN area_id BIGINT REFERENCES areas(id);

UPDATE activities
SET area_id = (
  SELECT id
  FROM areas
  WHERE name = 'Waterfront'
)
WHERE LOWER(name) = 'waterskiing';

UPDATE activities
SET area_id = (
  SELECT id
  FROM areas
  WHERE name = 'Athletics'
)
WHERE LOWER(name) = 'pickleball';

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM activities
    WHERE area_id IS NULL
  ) THEN
    RAISE EXCEPTION
      'Existing activities remain without an Area';
  END IF;
END
$$;

ALTER TABLE activities
ALTER COLUMN area_id SET NOT NULL;

CREATE TABLE qualifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE activity_qualifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id BIGINT NOT NULL REFERENCES activities(id),
  qualification_id BIGINT NOT NULL REFERENCES qualifications(id),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  UNIQUE (activity_id, qualification_id)
);

CREATE TABLE staff_qualifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_member_id BIGINT NOT NULL REFERENCES staff_members(id),
  qualification_id BIGINT NOT NULL REFERENCES qualifications(id),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  UNIQUE (staff_member_id, qualification_id)
);

COMMIT;
