BEGIN;

CREATE TABLE event_registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  event_id BIGINT NOT NULL REFERENCES events(id),
  spots_paid_for INTEGER NOT NULL CHECK (spots_paid_for > 0),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  CONSTRAINT event_registrations_user_event_unique
    UNIQUE (user_id, event_id)
);

ALTER TABLE member_attendees
ADD CONSTRAINT member_attendees_member_event_unique
UNIQUE (member_id, event_id);

CREATE OR REPLACE FUNCTION enforce_event_registration_capacity()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  household_user_id BIGINT;
  paid_spots INTEGER;
  used_spots INTEGER;
BEGIN
  SELECT user_id
  INTO household_user_id
  FROM user_members
  WHERE id = NEW.member_id;

  SELECT spots_paid_for
  INTO paid_spots
  FROM event_registrations
  WHERE user_id = household_user_id
    AND event_id = NEW.event_id
  FOR UPDATE;

  IF paid_spots IS NULL THEN
    RAISE EXCEPTION 'EVENT_REGISTRATION_REQUIRED';
  END IF;

  SELECT COUNT(*)::INTEGER
  INTO used_spots
  FROM member_attendees ma
  JOIN user_members um
    ON um.id = ma.member_id
  WHERE um.user_id = household_user_id
    AND ma.event_id = NEW.event_id
    AND (
      TG_OP = 'INSERT'
      OR ma.id <> NEW.id
    );

  IF used_spots >= paid_spots THEN
    RAISE EXCEPTION 'EVENT_REGISTRATION_SPOTS_FULL';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER member_attendees_registration_capacity
BEFORE INSERT OR UPDATE OF member_id, event_id
ON member_attendees
FOR EACH ROW
EXECUTE FUNCTION enforce_event_registration_capacity();

CREATE OR REPLACE FUNCTION protect_event_registration_capacity()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  selected_count INTEGER;
BEGIN
  SELECT COUNT(*)::INTEGER
  INTO selected_count
  FROM member_attendees ma
  JOIN user_members um
    ON um.id = ma.member_id
  WHERE um.user_id = NEW.user_id
    AND ma.event_id = NEW.event_id;

  IF NEW.spots_paid_for < selected_count THEN
    RAISE EXCEPTION 'EVENT_REGISTRATION_BELOW_SELECTED_ATTENDEES';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER event_registrations_capacity_guard
BEFORE UPDATE OF user_id, event_id, spots_paid_for
ON event_registrations
FOR EACH ROW
EXECUTE FUNCTION protect_event_registration_capacity();

CREATE TRIGGER audit_row_change
AFTER INSERT OR UPDATE OR DELETE ON event_registrations
FOR EACH ROW
EXECUTE FUNCTION matapon_audit_row_change();

COMMIT;
