BEGIN;

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  must_change_password BOOLEAN NOT NULL DEFAULT TRUE,
  user_type TEXT NOT NULL
    CHECK (user_type IN ('member', 'staff', 'admin')),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE user_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  full_name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  dietary_restrictions TEXT,
  member_role TEXT NOT NULL
    CHECK (member_role IN ('primary', 'adult', 'child')),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE event_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  event_type_id BIGINT NOT NULL REFERENCES event_types(id),
  starts_at TEXT NOT NULL,
  ends_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE event_type_others (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES events(id),
  value TEXT NOT NULL,
  reason TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE staff_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  full_name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  role TEXT NOT NULL
    CHECK (role IN ('staff', 'manager')),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE staff_areas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE staff_member_areas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_member_id BIGINT NOT NULL REFERENCES staff_members(id),
  staff_area_id BIGINT NOT NULL REFERENCES staff_areas(id),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  setting TEXT NOT NULL
    CHECK (setting IN ('inside', 'outside', 'other')),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE activity_others (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id BIGINT NOT NULL REFERENCES activities(id),
  value TEXT NOT NULL,
  reason TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE staff_activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_member_id BIGINT NOT NULL REFERENCES staff_members(id),
  activity_id BIGINT NOT NULL REFERENCES activities(id),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE event_activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL REFERENCES events(id),
  activity_id BIGINT NOT NULL REFERENCES activities(id),
  starts_at TEXT NOT NULL,
  ends_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE event_activity_staff (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_activity_id BIGINT NOT NULL REFERENCES event_activities(id),
  staff_member_id BIGINT NOT NULL REFERENCES staff_members(id),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE member_attendees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT NOT NULL REFERENCES user_members(id),
  event_id BIGINT NOT NULL REFERENCES events(id),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE TABLE event_activity_signups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_activity_id BIGINT NOT NULL REFERENCES event_activities(id),
  member_attendee_id BIGINT NOT NULL REFERENCES member_attendees(id),
  checked_in_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text,
  CONSTRAINT event_activity_signups_event_activity_member_attendee_unique
    UNIQUE (event_activity_id, member_attendee_id)
);

COMMIT;

ALTER TABLE staff_activities
ADD CONSTRAINT staff_activities_staff_member_activity_unique
UNIQUE (staff_member_id, activity_id);

CREATE TABLE audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name TEXT NOT NULL,
  row_id TEXT NOT NULL,
  action TEXT NOT NULL CHECK (action IN ('INSERT', 'UPDATE', 'DELETE')),
  old_values JSONB,
  new_values JSONB,
  actor_user_id BIGINT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::text
);

CREATE OR REPLACE FUNCTION matapon_audit_row_change()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  actor_text TEXT;
  actor_id BIGINT;
  changed_row_id TEXT;
BEGIN
  actor_text := current_setting('matapon.actor_user_id', true);

  IF actor_text IS NOT NULL AND actor_text ~ '^[0-9]+$' THEN
    actor_id := actor_text::BIGINT;
  ELSE
    actor_id := NULL;
  END IF;

  IF TG_OP = 'DELETE' THEN
    changed_row_id := to_jsonb(OLD)->>'id';

    INSERT INTO audit_log (
      table_name,
      row_id,
      action,
      old_values,
      new_values,
      actor_user_id
    )
    VALUES (
      TG_TABLE_NAME,
      changed_row_id,
      'DELETE',
      to_jsonb(OLD),
      NULL,
      actor_id
    );

    RETURN OLD;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    changed_row_id := to_jsonb(NEW)->>'id';

    INSERT INTO audit_log (
      table_name,
      row_id,
      action,
      old_values,
      new_values,
      actor_user_id
    )
    VALUES (
      TG_TABLE_NAME,
      changed_row_id,
      'UPDATE',
      to_jsonb(OLD),
      to_jsonb(NEW),
      actor_id
    );

    RETURN NEW;
  END IF;

  changed_row_id := to_jsonb(NEW)->>'id';

  INSERT INTO audit_log (
    table_name,
    row_id,
    action,
    old_values,
    new_values,
    actor_user_id
  )
  VALUES (
    TG_TABLE_NAME,
    changed_row_id,
    'INSERT',
    NULL,
    to_jsonb(NEW),
    actor_id
  );

  RETURN NEW;
END;
$$;

DO $$
DECLARE
  table_name_to_audit TEXT;
BEGIN
  FOREACH table_name_to_audit IN ARRAY ARRAY[
    'users',
    'user_members',
    'event_types',
    'events',
    'event_type_others',
    'staff_members',
    'staff_areas',
    'staff_member_areas',
    'activities',
    'activity_others',
    'staff_activities',
    'event_activities',
    'event_activity_staff',
    'member_attendees',
    'event_activity_signups'
  ]
  LOOP
    EXECUTE format(
      'CREATE TRIGGER audit_row_change
       AFTER INSERT OR UPDATE OR DELETE ON %I
       FOR EACH ROW
       EXECUTE FUNCTION matapon_audit_row_change()',
      table_name_to_audit
    );
  END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION prevent_audit_log_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'audit_log is append-only';
END;
$$;

CREATE TRIGGER audit_log_no_update_delete
BEFORE UPDATE OR DELETE ON audit_log
FOR EACH ROW
EXECUTE FUNCTION prevent_audit_log_mutation();

CREATE TRIGGER audit_log_no_truncate
BEFORE TRUNCATE ON audit_log
FOR EACH STATEMENT
EXECUTE FUNCTION prevent_audit_log_mutation();

CREATE UNIQUE INDEX user_members_one_primary_per_household
ON user_members (user_id)
WHERE member_role = 'primary';

CREATE OR REPLACE FUNCTION enforce_household_primary()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF OLD.member_role = 'primary'
       AND EXISTS (
         SELECT 1
         FROM user_members
         WHERE user_id = OLD.user_id
           AND id <> OLD.id
       )
    THEN
      RAISE EXCEPTION 'HOUSEHOLD_PRIMARY_REQUIRED';
    END IF;

    RETURN OLD;
  END IF;

  IF TG_OP = 'UPDATE'
     AND OLD.member_role = 'primary'
     AND (
       NEW.member_role <> 'primary'
       OR NEW.user_id <> OLD.user_id
     )
     AND EXISTS (
       SELECT 1
       FROM user_members
       WHERE user_id = OLD.user_id
         AND id <> OLD.id
     )
  THEN
    RAISE EXCEPTION 'HOUSEHOLD_PRIMARY_REQUIRED';
  END IF;

  IF NEW.member_role <> 'primary' THEN
    IF TG_OP = 'INSERT' THEN
      IF NOT EXISTS (
        SELECT 1
        FROM user_members
        WHERE user_id = NEW.user_id
          AND member_role = 'primary'
      )
      THEN
        RAISE EXCEPTION 'FIRST_HOUSEHOLD_MEMBER_MUST_BE_PRIMARY';
      END IF;
    ELSE
      IF NOT EXISTS (
        SELECT 1
        FROM user_members
        WHERE user_id = NEW.user_id
          AND member_role = 'primary'
          AND id <> OLD.id
      )
      THEN
        RAISE EXCEPTION 'HOUSEHOLD_PRIMARY_REQUIRED';
      END IF;
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER enforce_household_primary_trigger
BEFORE INSERT OR UPDATE OR DELETE ON user_members
FOR EACH ROW
EXECUTE FUNCTION enforce_household_primary();


CREATE OR REPLACE FUNCTION enforce_event_activity_signup_rules()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  requested_member_id BIGINT;
  attendee_event_id BIGINT;
  requested_event_id BIGINT;
  requested_start TIMESTAMPTZ;
  requested_end TIMESTAMPTZ;
  requested_activity_name TEXT;
  current_signup_id BIGINT;
  conflicting_activity_name TEXT;
  conflicting_start TEXT;
  conflicting_end TEXT;
BEGIN
  IF TG_OP = 'UPDATE' THEN
    current_signup_id := OLD.id;
  ELSE
    current_signup_id := NULL;
  END IF;

  SELECT ma.member_id, ma.event_id
  INTO requested_member_id, attendee_event_id
  FROM member_attendees ma
  WHERE ma.id = NEW.member_attendee_id;

  IF NOT FOUND THEN
    RETURN NEW;
  END IF;

  PERFORM pg_advisory_xact_lock(requested_member_id);

  SELECT
    ea.event_id,
    ea.starts_at::timestamptz,
    ea.ends_at::timestamptz,
    a.name
  INTO
    requested_event_id,
    requested_start,
    requested_end,
    requested_activity_name
  FROM event_activities ea
  JOIN activities a ON a.id = ea.activity_id
  WHERE ea.id = NEW.event_activity_id;

  IF NOT FOUND THEN
    RETURN NEW;
  END IF;

  IF requested_event_id <> attendee_event_id THEN
    RAISE EXCEPTION USING
      ERRCODE = 'P0001',
      MESSAGE = 'ACTIVITY_SIGNUP_EVENT_MISMATCH';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM event_activity_signups existing_signup
    JOIN member_attendees existing_attendee
      ON existing_attendee.id = existing_signup.member_attendee_id
    WHERE existing_signup.event_activity_id = NEW.event_activity_id
      AND existing_attendee.member_id = requested_member_id
      AND (
        current_signup_id IS NULL
        OR existing_signup.id <> current_signup_id
      )
  ) THEN
    RAISE EXCEPTION USING
      ERRCODE = 'P0001',
      MESSAGE = 'ACTIVITY_SIGNUP_DUPLICATE',
      DETAIL = json_build_object(
        'activity_name',
        requested_activity_name
      )::text;
  END IF;

  SELECT
    conflicting_activity.name,
    conflicting_event_activity.starts_at,
    conflicting_event_activity.ends_at
  INTO
    conflicting_activity_name,
    conflicting_start,
    conflicting_end
  FROM event_activity_signups existing_signup
  JOIN member_attendees existing_attendee
    ON existing_attendee.id = existing_signup.member_attendee_id
  JOIN event_activities conflicting_event_activity
    ON conflicting_event_activity.id = existing_signup.event_activity_id
  JOIN activities conflicting_activity
    ON conflicting_activity.id = conflicting_event_activity.activity_id
  WHERE existing_attendee.member_id = requested_member_id
    AND existing_signup.event_activity_id <> NEW.event_activity_id
    AND (
      current_signup_id IS NULL
      OR existing_signup.id <> current_signup_id
    )
    AND requested_start < conflicting_event_activity.ends_at::timestamptz
    AND requested_end > conflicting_event_activity.starts_at::timestamptz
  ORDER BY
    conflicting_event_activity.starts_at::timestamptz,
    existing_signup.id
  LIMIT 1;

  IF FOUND THEN
    RAISE EXCEPTION USING
      ERRCODE = 'P0001',
      MESSAGE = 'ACTIVITY_TIME_CONFLICT',
      DETAIL = json_build_object(
        'activity_name',
        conflicting_activity_name,
        'starts_at',
        conflicting_start,
        'ends_at',
        conflicting_end
      )::text;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER enforce_event_activity_signup_rules_trigger
BEFORE INSERT OR UPDATE ON event_activity_signups
FOR EACH ROW
EXECUTE FUNCTION enforce_event_activity_signup_rules();
